# Generated by Django 6.0.5 on 2026-05-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinebrand',
            name='brand',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='machinecategory',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
